<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://persondata.org/auditerror"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:ns0="http://persondata.org/auditerror/"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../Metadata/xsds/ErrorAudit_v5.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AuditLogRequest" namespace="http://persondata.org/auditerror/"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Interfaces/TargetSchemas/AuditLogRequestNative.xsd"/>
        <oracle-xsl-mapper:rootElement name="AuditLogRequest" namespace="http://persondata.org/auditerror"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAR 19 14:37:33 SAST 2026].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:AuditLogRequest>
      <tns:messageUID>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:messageUID"/>
      </tns:messageUID>
      <tns:transactionId>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:transactionId"/>
      </tns:transactionId>
      <tns:componentName>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:componentName"/>
      </tns:componentName>
      <tns:applicationServerId>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:applicationServerId"/>
      </tns:applicationServerId>
      <tns:businessKeys>
        <tns:keyName>
          <xsl:value-of select="/ns0:AuditLogRequest/ns0:businessKeys/ns0:businessKey/ns0:keyName"/>
        </tns:keyName>
        <tns:keyValue>
          <xsl:value-of select="/ns0:AuditLogRequest/ns0:businessKeys/ns0:businessKey/ns0:keyValue"/>
        </tns:keyValue>
      </tns:businessKeys>
      <tns:description>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:description"/>
      </tns:description>
      <tns:txnSourceCreateTimestamp>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:txnSourceCreateTimestamp"/>
      </tns:txnSourceCreateTimestamp>
      <tns:startTimestamp>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:startTimestamp/@xsi:nil"/>
      </tns:startTimestamp>
      <tns:endTimestamp>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:endTimestamp/@xsi:nil"/>
      </tns:endTimestamp>
      <tns:message>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:message"/>
      </tns:message>
      <tns:environment>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:environment"/>
      </tns:environment>
      <tns:auditType>
        <xsl:value-of select="/ns0:AuditLogRequest/ns0:auditType"/>
      </tns:auditType>
    </tns:AuditLogRequest>
  </xsl:template>
</xsl:stylesheet>
